# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

build:
  maxIssues: 17 #todo: zero out

comments:
  UndocumentedPublicClass:
    active: true

formatting:
  Indentation:
    active: true
  CommentSpacing:
    active: false
  NoWildcardImports:
    active: false

style:
  ForbiddenComment:
    active: false
  ReturnCount:
    active: false
  WildcardImport:
    active: false
